/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Gym.Manager;

import Business.Employee.Employee;
import Business.Enterprise.GymEnterprise;
import Business.Network.Network;
import Business.Accounts.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author krishna
 */
public class EmployeeViewJPanel extends javax.swing.JPanel {
    private JPanel container;
    private UserAccount account;
    private GymEnterprise fitenterprise;
    private Network network;
    /**
     * Creates new form EmployeeViewJPanel
     */
    public EmployeeViewJPanel(JPanel container, UserAccount account, GymEnterprise fitenterprise, Network network) {
        initComponents();
        this.container = container;
        this.account = account;
        this.fitenterprise = fitenterprise;
        this.network = network;
        populateEmployee();
    }

    
    
    public void populateEmployee() {
        DefaultTableModel model = (DefaultTableModel) viewEmployeeJTable.getModel();
        
        model.setRowCount(0);
        fitenterprise.getEmployeeDirectory().getEmployeeList();
        for(Employee employee : fitenterprise.getEmployeeDirectory().getEmployeeList()){
            Object[] row = new Object[3];
            row[0] = employee.getId();
            row[1] = employee;
            row[2] = employee.getJobtitle();
            model.addRow(row);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        viewEmployeeJTable = new javax.swing.JTable();
        viewDetailsjButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backjButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        deleteEmployeeButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewEmployeeJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Employee name", "Title"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        viewEmployeeJTable.setRowHeight(40);
        viewEmployeeJTable.setRowMargin(4);
        viewEmployeeJTable.setSelectionBackground(new java.awt.Color(215, 145, 54));
        jScrollPane1.setViewportView(viewEmployeeJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 631, 284));

        viewDetailsjButton1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        viewDetailsjButton1.setForeground(new java.awt.Color(102, 102, 255));
        viewDetailsjButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/Business/details.png"))); // NOI18N
        viewDetailsjButton1.setText("Show employee details");
        viewDetailsjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailsjButton1ActionPerformed(evt);
            }
        });
        add(viewDetailsjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 570, 270, 40));

        jLabel1.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/Business/gear.png"))); // NOI18N
        jLabel1.setText("Current employees under you..");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, -1, -1));

        backjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/Business/goback.png"))); // NOI18N
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });
        add(backjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 720, 80, 50));

        addButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        addButton.setForeground(new java.awt.Color(102, 102, 255));
        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/Business/plus.png"))); // NOI18N
        addButton.setText("Add a new employee");
        addButton.setPreferredSize(new java.awt.Dimension(190, 25));
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 570, 250, 40));

        deleteEmployeeButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        deleteEmployeeButton.setForeground(new java.awt.Color(255, 51, 51));
        deleteEmployeeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/Business/minus.png"))); // NOI18N
        deleteEmployeeButton.setText("Remove selected employee");
        deleteEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEmployeeButtonActionPerformed(evt);
            }
        });
        add(deleteEmployeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 650, 300, 40));

        jLabel2.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        jLabel2.setText("Select an action as required...");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 480, 360, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void viewDetailsjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailsjButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = viewEmployeeJTable.getSelectedRow();
        if(selectedRow >= 0){
            Employee employee = (Employee)viewEmployeeJTable.getValueAt(selectedRow, 1);
            EmployeeDetailJPanel employeeDetailJPanel = new EmployeeDetailJPanel(container, employee);
            container.add("employeeDetailJPanel", employeeDetailJPanel);
            CardLayout layout = (CardLayout) container.getLayout();
            layout.next(container);
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
    }//GEN-LAST:event_viewDetailsjButton1ActionPerformed

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backjButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        AddEmployeeJPanel addEmployeeJPanel = new AddEmployeeJPanel(container, fitenterprise, network);
        container.add("addEmployeeJPanel", addEmployeeJPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEmployeeButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = viewEmployeeJTable.getSelectedRow();
        if(selectedRow >= 0){
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure to delete?","Warning",selectionButton);
            if(selectionResult == JOptionPane.YES_OPTION){
                Employee employee = (Employee)viewEmployeeJTable.getValueAt(selectedRow, 1);
                fitenterprise.getEmployeeDirectory().getEmployeeList().remove(employee);
                populateEmployee();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
    }//GEN-LAST:event_deleteEmployeeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton backjButton;
    private javax.swing.JButton deleteEmployeeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton viewDetailsjButton1;
    private javax.swing.JTable viewEmployeeJTable;
    // End of variables declaration//GEN-END:variables    
}
