/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Customer;
import Business.Booking.Booking;
import Business.Enterprise.GymEnterprise;
import Business.Accounts.UserAccount;
import Business.WorkQueue.BookingRequest;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author krishna
 */
public class RequestTrainerJPanel extends javax.swing.JPanel {
    private JPanel container;
    private UserAccount account;
    private GymEnterprise gymenterprise;
    private DateFormat df;
    /**
     * Creates new form RequestTrainerJPanel
     */
    public RequestTrainerJPanel(JPanel container, UserAccount account, GymEnterprise fitenterprise) {
        initComponents();
        this.container = container;
        this.account = account;
        this.gymenterprise = fitenterprise;
        //df = new SimpleDateFormat("yyyy-MM-dd");
        df = new SimpleDateFormat("YYYY/MM/DD");
        populateComboBox();
    }
    public void populateComboBox() {
        cbxDateSelect.removeAll();
        for(Date date : gymenterprise.getAppointmentTime().getDateList()){
            cbxDateSelect.addItem(df.format(date));
        }
        cbxTimeSlotSelect.removeAll();
        for(String session : gymenterprise.getAppointmentTime().getSessionList()){
            cbxTimeSlotSelect.addItem(session);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backjButton = new javax.swing.JButton();
        BtnReserve = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cbxDateSelect = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbxTimeSlotSelect = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        backjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/goback.png"))); // NOI18N
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        BtnReserve.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnReserve.setForeground(new java.awt.Color(102, 102, 255));
        BtnReserve.setText("Confirm selected appointment");
        BtnReserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReserveActionPerformed(evt);
            }
        });

        viewBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        viewBtn.setForeground(new java.awt.Color(102, 102, 255));
        viewBtn.setText("Show appointment status");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));

        cbxDateSelect.setToolTipText("");
        cbxDateSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDateSelectActionPerformed(evt);
            }
        });
        cbxDateSelect.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbxDateSelectKeyPressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/calendar.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        jLabel8.setText("Select a time slot as per your convenience");

        cbxTimeSlotSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTimeSlotSelectActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/clock.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxDateSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxTimeSlotSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(71, 71, 71))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbxDateSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(cbxTimeSlotSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel2)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(backjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135)
                        .addComponent(BtnReserve)
                        .addGap(18, 18, 18)
                        .addComponent(viewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(687, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BtnReserve, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(viewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(132, 132, 132))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backjButtonActionPerformed

    private void cbxDateSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDateSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDateSelectActionPerformed

    private void cbxTimeSlotSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTimeSlotSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTimeSlotSelectActionPerformed

    private void BtnReserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReserveActionPerformed
        // TODO add your handling code here:
        String dateString = (String) cbxDateSelect.getSelectedItem();
        Date date = null;
        try {
            date = df.parse(dateString);
        } catch (ParseException ex) {
            Logger.getLogger(RequestTrainerJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        String session = (String) cbxTimeSlotSelect.getSelectedItem();
        for(BookingRequest appointmentRequest : account.getAppointmentQueue().getAppointmentRequestList()){
            if((appointmentRequest.getStatus().equals("Accept") || appointmentRequest.getStatus().equals("Pending")) && appointmentRequest.getAppointment().getDate().equals(date) && appointmentRequest.getAppointment().getSession().equals(session)){
                JOptionPane.showMessageDialog(null, "You already have appointment at that time");
                return;
            }
        }
        JOptionPane.showMessageDialog(null, "Successfully");
        Booking appointment = new Booking(date, session);
        BookingRequest appointmentRequest = new BookingRequest(appointment);
        appointmentRequest.setSender(account);
        appointmentRequest.setStatus("Pending");
        account.getAppointmentQueue().getAppointmentRequestList().add(appointmentRequest);
        gymenterprise.getBookingQueue().getAppointmentRequestList().add(appointmentRequest);
    }//GEN-LAST:event_BtnReserveActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:
        ViewReservationJPanel requestViewJPanel = new ViewReservationJPanel(container, account, gymenterprise);
        container.add("requestViewJPanel", requestViewJPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_viewBtnActionPerformed

    private void cbxDateSelectKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbxDateSelectKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDateSelectKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnReserve;
    private javax.swing.JButton backjButton;
    private javax.swing.JComboBox cbxDateSelect;
    private javax.swing.JComboBox cbxTimeSlotSelect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables

    
}
