/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Gym.Trainer;

import Business.Program.Program;
import Business.Enterprise.GymEnterprise;
import Business.Accounts.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author sanket
 */
public class AddNewProgramJPanel extends javax.swing.JPanel {
    private JPanel container;
    private UserAccount account;
   
    private GymEnterprise gymEnterprise;
    /**
     * Creates new form AddCourseJPanel
     */


    public AddNewProgramJPanel(JPanel container, GymEnterprise gymEnterprise) {
        initComponents();
        this.container = container;
        this.gymEnterprise = gymEnterprise;
        
        txtProgramID.setText(String.valueOf(Program.getCount()));
        txtProgramID.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtProgramID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnAddProgram = new javax.swing.JButton();
        txtSeatCount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtProgramName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDiff = new javax.swing.JTextField();
        btnViewYourPrograms = new javax.swing.JButton();
        lblSeatErrMesg = new javax.swing.JLabel();

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/goback.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel3.setText("How many seats?");

        txtProgramID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProgramIDActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter program ID");

        btnAddProgram.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnAddProgram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/plus.png"))); // NOI18N
        btnAddProgram.setText("Add this program");
        btnAddProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProgramActionPerformed(evt);
            }
        });

        txtSeatCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeatCountActionPerformed(evt);
            }
        });
        txtSeatCount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSeatCountKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel5.setText("Enter program details");

        jLabel1.setText("Enter program name");

        txtProgramName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProgramNameActionPerformed(evt);
            }
        });

        jLabel4.setText("Set difficulty level");

        btnViewYourPrograms.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        btnViewYourPrograms.setText("View your added programs");
        btnViewYourPrograms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewYourProgramsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(97, 97, 97)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSeatCount)
                                    .addComponent(txtProgramName)
                                    .addComponent(txtProgramID)
                                    .addComponent(txtDiff, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(29, 29, 29)
                        .addComponent(lblSeatErrMesg, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnAddProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(btnViewYourPrograms))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProgramName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtProgramID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSeatCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(lblSeatErrMesg, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDiff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnViewYourPrograms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
    }// </editor-fold>                        

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        Component[] componentArray = container.getComponents();
        
        Component component = componentArray[componentArray.length - 1];
        ViewAddedProgramsJPanel courseViewPanel = (ViewAddedProgramsJPanel) component;
        
        courseViewPanel.populateCourse();
        
        layout.previous(container);
    }                                       

    private void txtProgramIDActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void btnAddProgramActionPerformed(java.awt.event.ActionEvent evt) {                                              
        
        int i = 0;
        
      // i = Integer.parseInt(txtSeatCount.getText());
       
       if (txtProgramName.getText().equals("")  ||  txtDiff.getText().equals("") || txtSeatCount.getText().equals ("") ){
           
          JOptionPane.showMessageDialog(null, "Enter all the mandatory fields");
          
    }
       else{
           
       i = Integer.parseInt(txtSeatCount.getText());
       
       if (i < 100 && i > 10)
       {
            
                
                try{

                    Integer d = Integer.parseInt(txtSeatCount.getText());
                    
                }
                catch(NumberFormatException e){
                    
                    JOptionPane.showMessageDialog(null, "Only digits allowed as seat count");
                    return;
                    
                }

                Program course  = new Program(txtProgramName.getText(), Integer.parseInt(txtSeatCount.getText()), txtDiff.getText());
                gymEnterprise.getProgramDirectory().getProgramList().add(course);
                txtProgramName.setText("");
                txtSeatCount.setText("");
                JOptionPane.showMessageDialog(null, "Added successfully");
            
       }
       else
       {
           JOptionPane.showMessageDialog(null, "The seat count must be between 10 to 100, please enter a value accordingly");
       }

       }
       
       
    }                                             

    private void txtSeatCountActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void txtProgramNameActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void btnViewYourProgramsActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        
        ViewAddedProgramsJPanel programsView = new ViewAddedProgramsJPanel(container, account, gymEnterprise);
        container.add ("programsView", programsView);
        
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }                                                   

    private void txtSeatCountKeyPressed(java.awt.event.KeyEvent evt) {                                        
        // TODO add your handling code here:
        
        if(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' )
        {
            txtSeatCount.setEditable  (true);
            
            txtSeatCount.setBackground (Color.WHITE);
            
            lblSeatErrMesg.setText ("");
            
        }
        
        else {
            
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE)
            {
                txtSeatCount.setEditable(true);
                
                 txtSeatCount.setBackground (Color.WHITE);
                 
                 lblSeatErrMesg.setText ("");
            }
            
            else {
                
                 txtSeatCount.setEditable (false);
                 
                 txtSeatCount.setBackground (Color.red);
                 
                 lblSeatErrMesg.setText ("You are not entering a digit..");
            }
        }
    }                                       


    // Variables declaration - do not modify                     
    private javax.swing.JButton btnAddProgram;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViewYourPrograms;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblSeatErrMesg;
    private javax.swing.JTextField txtDiff;
    private javax.swing.JTextField txtProgramID;
    private javax.swing.JTextField txtProgramName;
    private javax.swing.JTextField txtSeatCount;
    // End of variables declaration                   
}
